[package]
name = "xfily"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo = "0.8"
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "webp", "bmp"] }
web-sys = { version = "0.3", features = ["HtmlSelectElement"] }
yew = { version = "0.20", features = ["csr"] }
